In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



### what does the axis argument do in numpy.mean() ?

In [16]:
# 2D array
arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
               [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
               [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
               [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
               [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
               )
            
print(f"{arr.shape=}",
        f"{arr.mean().shape=}",
        f"{arr.mean(axis=0).shape=}",
        f"{arr.mean(axis=1).shape=}",
        f"{arr.mean()=}",
        f"{arr.mean(axis=0)=}",
        f"{arr.mean(axis=1)=}",
        sep="\n")

arr.shape=(5, 10)
arr.mean()=5.5
arr.mean(axis=0)=array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
arr.mean(axis=1)=array([5.5, 5.5, 5.5, 5.5, 5.5])
arr.mean().shape=()
arr.mean(axis=0).shape=(10,)
arr.mean(axis=1).shape=(5,)


In [20]:
# reshape into 3D array
arr2 = arr.reshape(5, 2, 5)

print(f"{arr2.shape=}",
        f"arr2 = \n {arr2}",
        f"{arr2.mean().shape=}",
        f"{arr2.mean(axis=0).shape=}",
        f"{arr2.mean(axis=1).shape=}",
        f"{arr2.mean(axis=2).shape=}",
        f"{arr2.mean()=}",
        f"{arr2.mean(axis=0)=}",
        f"{arr2.mean(axis=1)=}",
        f"{arr2.mean(axis=2)=}",
        sep="\n")

arr2.shape=(5, 2, 5)
arr2 = 
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
arr2.mean().shape=()
arr2.mean(axis=0).shape=(2, 5)
arr2.mean(axis=1).shape=(5, 5)
arr2.mean(axis=2).shape=(5, 2)
arr2.mean()=5.5
arr2.mean(axis=0)=array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])
arr2.mean(axis=1)=array([[3.5, 4.5, 5.5, 6.5, 7.5],
       [3.5, 4.5, 5.5, 6.5, 7.5],
       [3.5, 4.5, 5.5, 6.5, 7.5],
       [3.5, 4.5, 5.5, 6.5, 7.5],
       [3.5, 4.5, 5.5, 6.5, 7.5]])
arr2.mean(axis=2)=array([[3., 8.],
       [3., 8.],
       [3., 8.],
       [3., 8.],
       [3., 8.]])
